WRAP_CLASS("itk::SpatialObjectWriter")

  WRAP_INCLUDE_TYPE_AFTER_PRAGMA_MANAGED( "itkManagedSceneSpatialObject.cxx" )
  WRAP_INCLUDE_WRAPPER( "itkManagedSceneSpatialObject.cxx" )

  SET(MANAGED_TYPE_TEMPLATE ${MANAGED_ITK_SOURCE_COMMON_PATH}/itkManagedObject_TYPE.cxx.in)
  SET(MANAGED_WRAPPER_TEMPLATE ${MANAGED_ITK_SOURCE_COMMON_PATH}/itkManagedObject_WRAPPER.cxx.in)

  FOREACH(d ${WRAP_ITK_DIMS})
    FOREACH(t ${WRAP_ITK_SCALAR_NO_BOOL})
      WRAP_TEMPLATE("${ITKM_${t}}${d}" "${d},${ITKT_${t}}")
    ENDFOREACH(t)
  ENDFOREACH(d)

  BEGIN_MANAGED_PROPERTY("FileName" GETSET)
    SET(MANAGED_PROPERTY_SUMMARY   "Specify the file to write. This is forwarded to the IO instance.")
    SET(MANAGED_PROPERTY_TYPE      "String^")
    SET(MANAGED_PROPERTY_GET_BODY  "return gcnew String( m_PointerToNative->GetFileName() );")
    SET(MANAGED_PROPERTY_SET_BODY  "std::string stdvalue; ManagedTypes::ToNativeString( value, stdvalue ); m_PointerToNative->SetFileName( stdvalue.c_str() );")
  END_MANAGED_PROPERTY()

  BEGIN_MANAGED_PROPERTY("WriteImagesInSeparateFile" GETSET)
    SET(MANAGED_PROPERTY_SUMMARY   "Get/set if the images should be written in a different file.")
    SET(MANAGED_PROPERTY_TYPE      "bool")
    SET(MANAGED_PROPERTY_GET_BODY  "return m_PointerToNative->GetWriteImagesInSeparateFile();")
    SET(MANAGED_PROPERTY_SET_BODY  "m_PointerToNative->SetWriteImagesInSeparateFile( value );")
  END_MANAGED_PROPERTY()

  BEGIN_MANAGED_PROPERTY("BinaryPoints" GETSET)
    SET(MANAGED_PROPERTY_SUMMARY   "Get/set binary points.")
    SET(MANAGED_PROPERTY_TYPE      "bool")
    SET(MANAGED_PROPERTY_GET_BODY  "return m_PointerToNative->GetBinaryPoints();")
    SET(MANAGED_PROPERTY_SET_BODY  "m_PointerToNative->SetBinaryPoints( value );")
  END_MANAGED_PROPERTY()

  BEGIN_MANAGED_PROPERTY("TransformPrecision" GETSET)
    SET(MANAGED_PROPERTY_SUMMARY   "Get/set the transform precision.")
    SET(MANAGED_PROPERTY_TYPE      "unsigned int")
    SET(MANAGED_PROPERTY_GET_BODY  "return m_PointerToNative->GetTransformPrecision();")
    SET(MANAGED_PROPERTY_SET_BODY  "m_PointerToNative->SetTransformPrecision( value );")
  END_MANAGED_PROPERTY()

  BEGIN_MANAGED_METHOD("Update")
    SET(MANAGED_METHOD_SUMMARY         "Update the reader object.")
    SET(MANAGED_METHOD_RETURN_TYPE     "void")
    SET(MANAGED_METHOD_PARAMS          "void")
    SET(MANAGED_METHOD_TYPE_BODY       "try{ this->m_PointerToNative->Update( ); } catch ( itk::ExceptionObject& ex ){ throw gcnew itkExceptionObject( ex.GetDescription(), ex.GetLocation(), ex.GetFile(), ex.GetLine() ); }")
    SET(MANAGED_METHOD_WRAPPER_BODY    "iInstance->Update( );")
  END_MANAGED_METHOD()

  BEGIN_MANAGED_METHOD("SetInput")
    SET(MANAGED_METHOD_SUMMARY         "Set the spatial object input of the writer object.")
    SET(MANAGED_METHOD_RETURN_TYPE     "void")
    SET(MANAGED_METHOD_PARAMS          "IntPtr itkSpatialObjectPtr")
    SET(MANAGED_METHOD_TYPE_BODY       "this->m_PointerToNative->SetInput( (NativeType::SpatialObjectType*)itkSpatialObjectPtr.ToPointer() );")
    SET(MANAGED_METHOD_WRAPPER_BODY    "iInstance->SetInput( itkSpatialObjectPtr );")
  END_MANAGED_METHOD()
  
  BEGIN_MANAGED_METHOD("SetInput")
    SET(MANAGED_METHOD_SUMMARY         "Set the input of the writer object.")
    SET(MANAGED_METHOD_RETURN_TYPE     "void")
    SET(MANAGED_METHOD_PARAMS          "itkSpatialObjectBase^ object")
    SET(MANAGED_METHOD_TYPE_BODY       "this->m_PointerToNative->SetInput( (NativeType::SpatialObjectType*)object->NativePointer.ToPointer() );")
    SET(MANAGED_METHOD_WRAPPER_BODY    "iInstance->SetInput( object );")
  END_MANAGED_METHOD()
  
  BEGIN_MANAGED_METHOD("SetInput")
    SET(MANAGED_METHOD_SUMMARY         "Set the input of the writer object.")
    SET(MANAGED_METHOD_RETURN_TYPE     "void")
    SET(MANAGED_METHOD_PARAMS          "itkSceneSpatialObject^ scene")
    SET(MANAGED_METHOD_TYPE_BODY       "this->m_PointerToNative->SetInput( (NativeType::SceneType*)scene->NativePointer.ToPointer() );")
    SET(MANAGED_METHOD_WRAPPER_BODY    "iInstance->SetInput( scene );")
  END_MANAGED_METHOD()

END_WRAP_CLASS()