WRAP_CLASS("itk::IntensityWindowingImageFilter")

  WRAP_IMAGE_FILTER_USIGN_INT(2)
  WRAP_IMAGE_FILTER_SIGN_INT(2)
  WRAP_IMAGE_FILTER_REAL(2)

  SET(body "")
  SET(body "${body}\n\t\t// Convert from itkPixel to native format, and call function")
  SET(body "${body}\n\t\tInputImageType::PixelType windowNative = itk::ManagedTypes::ToNativePixel<InputImageType::PixelType>(  window );")
  SET(body "${body}\n\t\tInputImageType::PixelType levelNative = itk::ManagedTypes::ToNativePixel<InputImageType::PixelType>( level );")
  SET(body "${body}\n\t\tm_PointerToNative->SetWindowLevel(windowNative, levelNative);")

  BEGIN_MANAGED_METHOD("SetWindowLevel")
    SET(MANAGED_METHOD_SUMMARY         "Set the window and level values as itkPixels.")
    SET(MANAGED_METHOD_RETURN_TYPE     "void")
    SET(MANAGED_METHOD_PARAMS          "itkPixel^ window, itkPixel^ level")
    SET(MANAGED_METHOD_TYPE_BODY       "${body}")
    SET(MANAGED_METHOD_WRAPPER_BODY    "iInstance->SetWindowLevel( window, level );")
  END_MANAGED_METHOD()

  BEGIN_MANAGED_PROPERTY("OutputMinimum" GETSET)
    SET(MANAGED_PROPERTY_SUMMARY   "Get/set the output minimum value.")
    SET(MANAGED_PROPERTY_TYPE      "itkPixel^")
    SET(MANAGED_PROPERTY_GET_BODY  "return itk::ManagedTypes::ToManagedPixel<NativeType::OutputImageType::PixelType>( m_PointerToNative->GetOutputMinimum() );")
    SET(MANAGED_PROPERTY_SET_BODY  "m_PointerToNative->SetOutputMinimum( itk::ManagedTypes::ToNativePixel<NativeType::OutputImageType::PixelType>( value ) );")
  END_MANAGED_PROPERTY()
  
  BEGIN_MANAGED_PROPERTY("OutputMaximum" GETSET)
    SET(MANAGED_PROPERTY_SUMMARY   "Get/set the output maximum value.")
    SET(MANAGED_PROPERTY_TYPE      "itkPixel^")
    SET(MANAGED_PROPERTY_GET_BODY  "return itk::ManagedTypes::ToManagedPixel<NativeType::OutputImageType::PixelType>( m_PointerToNative->GetOutputMaximum() );")
    SET(MANAGED_PROPERTY_SET_BODY  "m_PointerToNative->SetOutputMaximum( itk::ManagedTypes::ToNativePixel<NativeType::OutputImageType::PixelType>( value ) );")
  END_MANAGED_PROPERTY()

  BEGIN_MANAGED_PROPERTY("WindowMinimum" GETSET)
    SET(MANAGED_PROPERTY_SUMMARY   "Get/set the window minimum value.")
    SET(MANAGED_PROPERTY_TYPE      "itkPixel^")
    SET(MANAGED_PROPERTY_GET_BODY  "return itk::ManagedTypes::ToManagedPixel<NativeType::InputImageType::PixelType>( m_PointerToNative->GetWindowMinimum() );")
    SET(MANAGED_PROPERTY_SET_BODY  "m_PointerToNative->SetWindowMinimum( itk::ManagedTypes::ToNativePixel<NativeType::InputImageType::PixelType>( value ) );")
  END_MANAGED_PROPERTY()
  
  BEGIN_MANAGED_PROPERTY("WindowMaximum" GETSET)
    SET(MANAGED_PROPERTY_SUMMARY   "Get/set the window maximum value.")
    SET(MANAGED_PROPERTY_TYPE      "itkPixel^")
    SET(MANAGED_PROPERTY_GET_BODY  "return itk::ManagedTypes::ToManagedPixel<NativeType::InputImageType::PixelType>( m_PointerToNative->GetWindowMaximum() );")
    SET(MANAGED_PROPERTY_SET_BODY  "m_PointerToNative->SetWindowMaximum( itk::ManagedTypes::ToNativePixel<NativeType::InputImageType::PixelType>( value ) );")
  END_MANAGED_PROPERTY()

  BEGIN_MANAGED_PROPERTY("CanRunInPlace" GET)
    SET(MANAGED_PROPERTY_SUMMARY   "Get if the filter can run in place. To do so, the filter's first input and output must have the same dimension and pixel type. This property can be used in conjunction with InPlace to determine whether a particular use of the filter is really running in place. Some filters may be able to optimize their operation if the InPlace is true and CanRunInPlace is true.")
    SET(MANAGED_PROPERTY_TYPE      "bool")
    SET(MANAGED_PROPERTY_GET_BODY  "return m_PointerToNative->CanRunInPlace();")
  END_MANAGED_PROPERTY()
  
  BEGIN_MANAGED_PROPERTY("InPlace" GETSET)
    SET(MANAGED_PROPERTY_SUMMARY   "Get/set if the filter will run in place. In place operation can be turned on and off. This only has an effect when the input and output image type match.")
    SET(MANAGED_PROPERTY_TYPE      "bool")
    SET(MANAGED_PROPERTY_GET_BODY  "return m_PointerToNative->GetInPlace();")
    SET(MANAGED_PROPERTY_SET_BODY  "m_PointerToNative->SetInPlace( value );")
  END_MANAGED_PROPERTY()

END_WRAP_CLASS()
