WRAP_CLASS("itk::CenteredEuler3DTransform")

  SET(MANAGED_TYPE_TEMPLATE ${MANAGED_ITK_SOURCE_COMMON_PATH}/itkManagedMatrixOffsetTransform_TYPE.cxx.in)
  SET(MANAGED_WRAPPER_TEMPLATE ${MANAGED_ITK_SOURCE_COMMON_PATH}/itkManagedMatrixOffsetTransform_WRAPPER.cxx.in)

  WRAP_TEMPLATE("${ITKM_D}3" "${ITKT_D}")

  BEGIN_MANAGED_METHOD("Translate")
    SET(MANAGED_METHOD_SUMMARY         "This method modifies self to include a translation of the origin. The translation is precomposed with self if pre is true, and postcomposed otherwise.")
    SET(MANAGED_METHOD_RETURN_TYPE     "void")
    SET(MANAGED_METHOD_PARAMS          "itkVector^ offset, bool pre")
    SET(MANAGED_METHOD_TYPE_BODY       "m_PointerToNative->Translate( itk::ManagedTypes::ToNativeVector<OutputVectorType::Dimension>(offset), pre );")
    SET(MANAGED_METHOD_WRAPPER_BODY    "iInstance->Translate( offset, pre );")
  END_MANAGED_METHOD()
  
  BEGIN_MANAGED_METHOD("Translate")
    SET(MANAGED_METHOD_SUMMARY         "This method modifies self to include a translation of the origin. The translation is postcomposed.")
    SET(MANAGED_METHOD_RETURN_TYPE     "void")
    SET(MANAGED_METHOD_PARAMS          "itkVector^ offset")
    SET(MANAGED_METHOD_TYPE_BODY       "this->Translate( offset, false );")
    SET(MANAGED_METHOD_WRAPPER_BODY    "iInstance->Translate( offset, false );")
  END_MANAGED_METHOD()

  BEGIN_MANAGED_METHOD("SetRotation")
    SET(MANAGED_METHOD_SUMMARY         "Set the rotational part of the transform.")
    SET(MANAGED_METHOD_RETURN_TYPE     "void")
    SET(MANAGED_METHOD_PARAMS          "double angleX, double angleY, double angleZ")
    SET(MANAGED_METHOD_TYPE_BODY       "m_PointerToNative->SetRotation( angleX, angleY, angleZ );")
    SET(MANAGED_METHOD_WRAPPER_BODY    "iInstance->SetRotation( angleX, angleY, angleZ );")
  END_MANAGED_METHOD()

  BEGIN_MANAGED_PROPERTY("AngleX" GET)
    SET(MANAGED_PROPERTY_SUMMARY   "Get/set the angle of rotation around the X-axis in radians.")
    SET(MANAGED_PROPERTY_TYPE      "double")
    SET(MANAGED_PROPERTY_GET_BODY  "return m_PointerToNative->GetAngleX();")
  END_MANAGED_PROPERTY()

  BEGIN_MANAGED_PROPERTY("AngleY" GET)
    SET(MANAGED_PROPERTY_SUMMARY   "Get/set the angle of rotation around the Y-axis in radians.")
    SET(MANAGED_PROPERTY_TYPE      "double")
    SET(MANAGED_PROPERTY_GET_BODY  "return m_PointerToNative->GetAngleY();")
  END_MANAGED_PROPERTY()
  
  BEGIN_MANAGED_PROPERTY("AngleZ" GET)
    SET(MANAGED_PROPERTY_SUMMARY   "Get/set the angle of rotation around the Z-axis in radians.")
    SET(MANAGED_PROPERTY_TYPE      "double")
    SET(MANAGED_PROPERTY_GET_BODY  "return m_PointerToNative->GetAngleZ();")
  END_MANAGED_PROPERTY()
  
  BEGIN_MANAGED_PROPERTY("ComputeZYX" GETSET)
    SET(MANAGED_PROPERTY_SUMMARY   "Get/set the order of the computation. Default ZXY.")
    SET(MANAGED_PROPERTY_TYPE      "bool")
    SET(MANAGED_PROPERTY_SET_BODY  "m_PointerToNative->SetComputeZYX( value );")
    SET(MANAGED_PROPERTY_GET_BODY  "return m_PointerToNative->GetComputeZYX();")
  END_MANAGED_PROPERTY()

END_WRAP_CLASS()
