WRAP_CLASS("itk::SceneSpatialObject")

  SET(MANAGED_TYPE_TEMPLATE ${MANAGED_ITK_SOURCE_MODULES_PATH}/${GROUP}/${SUBGROUP}/itkManagedSceneSpatialObject_TYPE.cxx.in)
  SET(MANAGED_WRAPPER_TEMPLATE ${MANAGED_ITK_SOURCE_MODULES_PATH}/${GROUP}/${SUBGROUP}/itkManagedSceneSpatialObject_WRAPPER.cxx.in)
  SET(MANGLED_PREFIX "SO")

  FOREACH(d ${WRAP_ITK_DIMS})
    WRAP_TEMPLATE("${d}" "${d}")
  ENDFOREACH(d)

END_WRAP_CLASS()
